### ISSUE TITLE
Linevast: some error encounter while testing plebnet

### ISSUE THREAD

**Issue by rpytel1** [MattSkala/cloudomate#20] opened 2018-12-01 16:48 UTC
while checking plebnet once I encounter such an error. Another execution of the command was successful and without any exceptions. 

```
vagrant@vagrant:~$ plebnet check
agent.core      : Checking PlebNet
  PID TTY          TIME CMD
                : No VPN configurations found!
Plebnet Check   : !!! VPN is not installed, child may get banned !!!
agent.core      : Tribler is already running
agent.core      : No provider chosen yet
                : An error occured!
                : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 41, in execute
    args.func()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 66, in execute_check
    agent.check()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 103, in check
    select_provider()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 317, in select_provider
    choice = cloudomate_controller.pick_provider(providers)
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 117, in pick_provider
    option, price, currency = pick_option(provider)
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 129, in pick_option
    vps_options = options(cloudomate_providers['vps'][provider])
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 102, in options
    return provider.get_options()
  File "/usr/local/lib/python2.7/dist-packages/cloudomate/hoster/vps/linevast.py", line 98, in get_options
    lst = list(options)
  File "/usr/local/lib/python2.7/dist-packages/cloudomate/hoster/vps/linevast.py", line 145, in _parse_openvz_hosting
    price = str(prices).split('data-monthly="')[index].split('" data-yearly=')[0]
IndexError: list index out of range 
```

**Comment by rpytel1** [comment] 2018-12-02 15:40
I somehow managed to reproduce the scenario thart will help you if it is relevant or not: 
1. create plebnet on testnet with ```bash install.sh develop 0 0```
2. ```plebnet check```
Then the error like above appears

After executing ```plebnet setup``` the following error didn't appeared.

**Comment by MattSkala** [comment] 2018-12-02 16:10
This was probably caused by PlebNet using an old version of cloudomate. Should be fixed now.

**Closed as completed** 2018-12-02 16:18 UTC

**Comment by rpytel1** [comment] 2018-12-02 16:28
I checked and you are right
